### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sr229** [vignetteapp/vignette-web#16]
I don't think we have the color schema for this but this has been requested by some folks who wanted dark mode for the website - and it has to reflect in the system theme and/or a toggle.

**Comment by imadatyatalah** [comment]
Hey @sr229!

Can you assign this issue to me?

**Comment by sr229** [comment]
> Hey @sr229!
> 
> Can you assign this issue to me?

Heya, I'd love to. What do you have in mind for this?

**Comment by imadatyatalah** [comment]
@sr229 I have checked the code and I found that you are using NextJS, Personally I love using [next-themes](https://www.npmjs.com/package/next-themes) because it has a lot of really cool features!

**Comment by Edqe14** [comment]
@imadatyatalah We currently use TailwindCSS which also have dark mode but if you think `next-themes` is better then feel free to use it

**Comment by imadatyatalah** [comment]
@Edqe14 We can use `next-themes` with `TailwindCSS`, Check out https://github.com/pacocoursey/next-themes#with-tailwind

**Comment by Edqe14** [comment]
> @Edqe14 We can use `next-themes` with `TailwindCSS`, Check out https://github.com/pacocoursey/next-themes#with-tailwind

I see, feel free to use it along with Tailwind then but I'm not sure what's the benefits of using `next-themes` instead of just using Tailwind built-in dark theme feature

**Comment by imadatyatalah** [comment]
@Edqe14 For me the major benefits of using `next-themes` is:
- No flash on load
- Force pages to specific themes
- 
This is all the benefits of using `next-themes`:
![Screenshot from 2021-10-02 19-37-32](https://user-images.githubusercontent.com/70093484/135728383-b1c6ddeb-ca55-4336-82a5-93091ccea70e.png)

**Comment by Edqe14** [comment]
I see, feel free to use it if you think it's worth it

**Comment by sr229** [comment]
> I see, feel free to use it if you think it's worth it

I don't think we should change our system just to accommodate themes, what we do want is just a toggle or an automatic way for the website to defer to switch to dark mode. So as much as possible, you can use the dark theme colors from Vignette Client for this.

**Comment by Edqe14** [comment]
> > I see, feel free to use it if you think it's worth it
> 
> I don't think we should change our system just to accommodate themes, what we do want is just a toggle or an automatic way for the website to defer to switch to dark mode. So as much as possible, you can use the dark theme colors from Vignette Client for this.

Tailwind already have pretty simple dark theme system so that's why I'm not sure what's the benefit of using `next-themes` with Tailwind since it's not much different (You could read the [dark theme docs](https://tailwindcss.com/docs/dark-mode) for Tailwind).

**Comment by JcdeA** [comment]
Tailwind has *very* good support for dark themes. We have no reason to pull in another library for dark mode.

**Comment by imadatyatalah** [comment]
> Tailwind has _very_ good support for dark themes. We have no reason to pull in another library for dark mode. buuut a library might make it much easier, so feel free to use it

Yes, `next-themes` makes working with themes much easier + more benefits!

**Comment by imadatyatalah** [comment]
Can someone assign this issue to me to start working on it?

**Comment by JcdeA** [comment]
@imadatyatalah assigned

**Comment by imadatyatalah** [comment]
@JcdeA Where should the toggle be?

**Comment by JcdeA** [comment]
Actually, that's a great question..

Our figma for the website didn't include a dark mode toggle.

What do you think about just doing media queries for now? Any suggestions where to put the toggle in if you think we need one?

**Comment by imadatyatalah** [comment]
@JcdeA What do you mean with **doing media queries**?

**Comment by Edqe14** [comment]
> @JcdeA What do you mean with **doing media queries**?

Maybe he meant tailwind dark mode `media` option

**Comment by JcdeA** [comment]
Yep - it auto detects whether or not to use dark mode by the device's settings.

**Comment by imadatyatalah** [comment]
@Edqe14 Ooooh I see, Can you give me a valid link to your discord server?

I'll search for some good color scheme for dark mode.

**Comment by Speykious** [comment]
> @Edqe14 Ooooh I see, Can you give me a valid link to your discord server?
> 
> I'll search for some good color scheme for dark mode.

https://discord.gg/db9xMywA

**Comment by JcdeA** [comment]
https://discord.gg/5FDCzv6F

**Comment by imadatyatalah** [comment]
> https://discord.gg/5FDCzv6F
> 
> Did the link expire?
> 
> @sr229 Can you check? You should set the invite as "never expire"

Yes, The link in the website is expired!

**Comment by JcdeA** [comment]
Ah we should update that

**Comment by sr229** [comment]
Implemented by GH-53
