### ISSUE TITLE
Add Vercel logo in the footer and sponsors list

### ISSUE THREAD

**Issue by sr229** [vignetteapp/vignette-web#9]
Just wanna let you guys know we still need to add the Vercel logo in the footer and link it according to the [guidelines](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project). Do it the same way or relatively the same way as we did it on docs.

**Comment by ShlokMohanty** [comment]
can i take on this issue @sr229  can you assign me this task?

**Comment by sr229** [comment]
Hello, sure thing, it's now assigned to you.

**Comment by ShlokMohanty** [comment]
thank @sr229  for assigning this to me

**Comment by ShlokMohanty** [comment]
@sr229  i wanted to ask that till how many days can we submit the pull request of the changes we add ?

**Comment by sr229** [comment]
I will give you 5 days to submit your PR, if you haven't provided any updates or a PR, I will re-assign it.

**Comment by ShlokMohanty** [comment]
so within 5 days i have to give you the updates right or the whole project ?

**Comment by sr229** [comment]
> so within 5 days i have to give you the updates right or the whole project ?

As much as possible the whole Pull Request.

**Comment by ShlokMohanty** [comment]
ok sure @sr229

**Comment by ShlokMohanty** [comment]
![Screenshot (639)_LI](https://user-images.githubusercontent.com/59838234/135762051-dca00783-fcd3-4095-9342-fb18168d47a7.jpg)

so @sr229 we have to add this logo in the footer right ?

**Comment by adryzz** [comment]
![image](https://user-images.githubusercontent.com/46694241/135762147-b27041c0-ed94-44c9-a88b-70e29d732ea5.png)
This one.

**Comment by JcdeA** [comment]
Yes

**Comment by adryzz** [comment]
<a href="https://vercel.com/?utm_source=vignette&utm_campaign=oss" target="_blank" rel="noreferrer noopener" aria-label="Powered by Vercel">
                    <img src="https://www.datocms-assets.com/31049/1618983297-powered-by-vercel.svg" alt="Powered by Vercel" />
                  </a>

**Comment by ShlokMohanty** [comment]
ok thanks @JcdeA and @adryzz

**Comment by ShlokMohanty** [comment]
@adryzz so do i have to put this line ?

**Comment by ShlokMohanty** [comment]
> ```
>               <a href="https://vercel.com/?utm_source=vignette&utm_campaign=oss" target="_blank" rel="noreferrer noopener" aria-label="Powered by Vercel">
>                 <img src="https://www.datocms-assets.com/31049/1618983297-powered-by-vercel.svg" alt="Powered by Vercel" />
>               </a>
> ```

like what this code is for?

**Comment by adryzz** [comment]
That's what has been put on [docs.vignetteapp.org](https://docs.vignetteapp.org) (the wiki) at least. I'm no webdev but i think it's that one.

**Comment by JcdeA** [comment]
> That's what has been put on [docs.vignetteapp.org](https://docs.vignetteapp.org) (the wiki) at least. I'm no webdev but i think it's that one.

It's https://wiki.vignetteapp.org btw

**Comment by JcdeA** [comment]
> > ```
> >               <a href="https://vercel.com/?utm_source=vignette&utm_campaign=oss" target="_blank" rel="noreferrer noopener" aria-label="Powered by Vercel">
> >                 <img src="https://www.datocms-assets.com/31049/1618983297-powered-by-vercel.svg" alt="Powered by Vercel" />
> >               </a>
> > ```
> 
> like what this code is for?
> 
> 

That's the vercel logo, in a link

**Comment by ShlokMohanty** [comment]
thanks @JcdeA for this thing

**Comment by sr229** [comment]
We're not limited to just that small badge, you can use the [Press Kit](https://vercel.com/design#dark-logotype) and just link it according to the guidelines @ShlokMohanty, so it looks cleaner.

**Comment by JcdeA** [comment]
@ShlokMohanty Sorry, but this was kinda time-sensative, so I implemented it in #!8

**Comment by ShlokMohanty** [comment]
but i guess timeline was for 5 days like i had 5 days with me as per told by @sr229 ?

**Comment by JcdeA** [comment]
I'm really sorry if you wanted to do it for hacktoberfest..

**Comment by ShlokMohanty** [comment]
no problem @JcdeA nothing like that so no need to worry
